FROM gitlab/gitlab-runner:latest

RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
    && echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get -y install docker-engine \
    && curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

RUN usermod -aG docker,www-data gitlab-runner

RUN echo 'gitlab-runner ALL=(ALL) NOPASSWD: /usr/bin/docker' >> /etc/sudoers
RUN echo 'gitlab-runner ALL=(ALL) NOPASSWD: /usr/sbin/service' >> /etc/sudoers